@startuml
class RemoveUserToTransactions <<partial>> {
    # <<override>> Up(migrationBuilder:MigrationBuilder) : void
    # <<override>> Down(migrationBuilder:MigrationBuilder) : void
}
Migration <|-- RemoveUserToTransactions
@enduml
