@startuml
class RemoveUserFKFromTransactions <<partial>> {
    # <<override>> Up(migrationBuilder:MigrationBuilder) : void
    # <<override>> Down(migrationBuilder:MigrationBuilder) : void
}
Migration <|-- RemoveUserFKFromTransactions
@enduml
