@startuml
class ArchitectureProjectController {
    - _balanceServiceMVC : IBalanceServiceMVC
    - _chargingServiceMVC : IChargingServiceMVC
    - _quotaConversionServiceMVC : IQuotaConversionServiceMVC
    + ArchitectureProjectController(balanceServiceMVC:IBalanceServiceMVC, chargingServiceMVC:IChargingServiceMVC, quotaConversionServiceMVC:IQuotaConversionServiceMVC)
    + Index() : IActionResult
    + ViewBalance() : IActionResult
    + <<async>> ViewBalance(username:string) : Task<IActionResult>
    + <<async>> SchoolToStudentList() : Task<IActionResult>
    + <<async>> SchoolToStudent(selectedUsernames:List<string>, amount:double) : Task<IActionResult>
    + RechargeByCard() : IActionResult
    + <<async>> RechargeByCard(model:CardRechargeModel) : Task<IActionResult>
}
Controller <|-- ArchitectureProjectController
@enduml
