@startuml
class ChargingServiceMVC {
    - <<readonly>> _httpClient : HttpClient
    - <<readonly>> _baseUrl : string = "https://localhost:7036/api/ArchitectureProjectAPI"
    + ChargingServiceMVC(httpClient:HttpClient)
    + <<async>> rechargeAccount(transactionM:TransactionM) : Task<TransactionM>
    + <<async>> UpdateBalanceAndQuota(userUpdate:UserBalanceModel) : Task<string>
}
IChargingServiceMVC <|-- ChargingServiceMVC
@enduml
