@startuml
interface IChargingServiceMVC {
    rechargeAccount(listTransactionM:List<TransactionM>) : Task<List<TransactionM>>
    UpdateBalanceAndQuota(userUpdate:UserBalanceModel) : Task<string>
    RechargeByCard(model:CardRechargeModel) : Task<string>
    GetAllUserBalance() : Task<List<UserBalanceModel>>
}
@enduml
