@startuml
class User {
    + UserId : int <<get>> <<set>>
    + <<required>> Username : string <<get>> <<set>>
    + IdCard : int <<get>> <<set>>
    + Balance : double <<get>> <<set>>
    + Quota : int <<get>> <<set>>
    + Transactions : ICollection<Transaction> <<get>> <<set>>
}
@enduml
