@startuml
class MS_SQLContext {
    + Users : DbSet<User> <<get>> <<set>>
    + MS_SQLContext(options:DbContextOptions<MS_SQLContext>)
    # <<override>> OnConfiguring(optionsBuilder:DbContextOptionsBuilder) : void
}
DbContext <|-- MS_SQLContext
@enduml
