@startuml
class PaymentContext {
    + Transactions : DbSet<Transaction> <<get>> <<set>>
    + PaymentContext(options:DbContextOptions<PaymentContext>)
    # <<override>> OnConfiguring(optionsBuilder:DbContextOptionsBuilder) : void
}
DbContext <|-- PaymentContext
@enduml
