@startuml
class BalanceService {
    - <<readonly>> _sqlContext : MS_SQLContext
    + BalanceService(sqlContext:MS_SQLContext)
    + <<async>> FetchBalanceByUsername(username:string) : Task<User>
}
IBalanceService <|-- BalanceService
@enduml
